package nl.hackyourfuture.project.backend.user.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.project.backend.user.User;
import java.time.OffsetDateTime;
import java.util.UUID;

@Schema(description = "A user account as returned by the API")
public record UserResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "effe1126-329f-4f31-942c-31bc0be4d672",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        UUID id,
        @Schema(
                description = "Email address of the user",
                example = "user@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,
        @Schema(
                description = "Name of the user",
                example = "John Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
                String name,
        @Schema(
                description = "When the user agreed to the terms and privacy policy. "
                        + "Null means they never did - show the agreement before continuing.",
                example = "2026-08-25T14:30:00Z"
        )
        OffsetDateTime termsAcceptedAt,
        @Schema(
                description = "When the account was created. Personal data under GDPR Art. 15, "
                        + "so it belongs in the data the user can download about themselves.",
                example = "2026-08-25T14:30:00Z",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        OffsetDateTime createdAt,
        @Schema(
                description = "The sign-in identity linked to this account, or null for a "
                        + "password-only account. Also Art. 15 data.",
                example = "google"
        )
        String oauthProvider,
        @Schema(
                description = "The account id at that provider, or null for a password-only account. "
                        + "Art. 15 data: it identifies which Google account, where oauthProvider only says that there is one.",
                example = "104928374651029384756"
        )
        String oauthProviderId,
        @Schema(
                description = "When the password was last set. Null for Google-only accounts, which have no password. "
                        + "For a fresh account this is the moment of registration, not a later change.",
                example = "2026-08-25T14:30:00Z"
        )
        OffsetDateTime passwordUpdatedAt
) {
    public static UserResponse from(User user) {
        return new UserResponse(
                user.getId(),
                user.getEmail(),
                user.getName(),
                user.getTermsAcceptedAt(),
                user.getCreatedAt(),
                user.getOauthProvider(),
                user.getOauthProviderId(),
                user.getPasswordUpdatedAt()
        );
    }
}
