export type ProfileSkillOption = {
  category: string;
  value: string;
};

export const PROFILE_SKILLS_BY_CATEGORY = {
  "DevOps & infrastructure": [
    "ci-cd",
    "devops",
    "automation",
    "kubernetes",
    "docker",
    "git",
    "observability",
    "infrastructure-as-code",
    "terraform",
    "networking",
    "linux",
    "azure-devops",
    "github",
    "ansible",
    "elk",
    "gitlab",
    "grafana",
    "jenkins",
    "prometheus",
    "github-actions",
    "helm",
    "version-control",
    "containerization",
    "gitops",
    "argocd",
    "opentelemetry",
    "datadog",
    "virtualization",
    "power-platform",
    "windows-server",
    "unix",
    "kibana",
    "power-automate",
    "bitbucket",
    "cmdb",
    "rhel",
    "intune",
    "nginx",
    "puppet",
    "rpa",
    "zapier",
    "sccm",
    "splunk",
    "dynatrace",
    "uipath",
    "loki",
    "cloudwatch",
    "ubuntu",
    "powerapps",
    "sentry",
  ],
  "Data engineering": [
    "sql",
    "data-pipelines",
    "data-engineering",
    "databricks",
    "etl",
    "data-quality",
    "spark",
    "elt",
    "kafka",
    "airflow",
    "dbt",
    "snowflake",
    "pyspark",
    "data-modeling",
    "data-governance",
    "microsoft-fabric",
    "data-warehousing",
    "azure-data-factory",
    "lakehouse",
    "data-lake",
    "delta-lake",
    "data-ingestion",
    "flink",
    "hadoop",
    "data-lineage",
    "rabbitmq",
    "workflow-orchestration",
    "metadata-management",
    "dagster",
    "sqs",
    "ssis",
    "azure-synapse",
    "mdm",
    "dimensional-modeling",
    "master-data-management",
    "nats",
    "sns",
    "prefect",
    "trino",
  ],
  "Cloud platforms": [
    "cloud",
    "azure",
    "aws",
    "gcp",
    "cloud-native",
    "openshift",
    "vmware",
    "lambda",
    "azure-functions",
    "pulumi",
    "aks",
    "bicep",
    "cloudformation",
    "ecs",
    "finops",
    "eks",
    "cdk",
    "ec2",
    "gke",
    "openstack",
    "vpc",
  ],
  "AI & machine learning": [
    "ai",
    "machine-learning",
    "data-science",
    "agentic-ai",
    "llm",
    "generative-ai",
    "mlops",
    "openai",
    "claude-code",
    "pytorch",
    "nlp",
    "prompt-engineering",
    "mcp",
    "deep-learning",
    "ai-enablement",
    "rag",
    "tensorflow",
    "langchain",
    "mlflow",
    "chatgpt",
    "pandas",
    "anthropic",
    "scikit-learn",
    "embeddings",
    "numpy",
    "vector-databases",
    "computer-vision",
    "github-copilot",
    "vector-search",
    "fine-tuning",
    "vertex-ai",
    "langgraph",
    "reinforcement-learning",
    "neural-networks",
    "sagemaker",
    "model-deployment",
    "conversational-ai",
    "jax",
    "semantic-search",
    "tensorrt",
    "anomaly-detection",
  ],
  "Programming languages": [
    "python",
    "java",
    "typescript",
    "javascript",
    "csharp",
    "bash",
    "cpp",
    "scala",
    "php",
    "kotlin",
    "powershell",
    "rust",
    "go",
    "ruby",
    "swift",
    "apex",
    "matlab",
    "vba",
    "assembly",
    "perl",
    "sas",
    "verilog",
    "elixir",
  ],
  "Business & domain": [
    "stakeholder-management",
    "saas",
    "crm",
    "business-development",
    "ecommerce",
    "salesforce",
    "sap",
    "erp",
    "go-to-market",
    "fintech",
    "account-executive",
    "candidate-experience",
    "pre-sales",
    "performance-management",
    "regulatory-compliance",
    "figma",
    "hubspot",
    "servicenow",
    "lead-generation",
    "pipeline-management",
    "seo",
    "demand-generation",
    "marketing-automation",
    "strategic-planning",
    "microsoft-dynamics",
    "embedded-systems",
    "financial-reporting",
    "embedded-software",
    "sap-s4hana",
    "sales-enablement",
    "sharepoint",
    "vendor-management",
    "service-desk",
    "copywriting",
    "cad",
    "influencer-marketing",
    "employee-relations",
    "employer-branding",
    "firmware",
    "fpga",
    "autocad",
    "canva",
    "paid-social",
    "sales-engineering",
    "typography",
    "photoshop",
    "succession-planning",
    "zendesk",
    "google-ads",
    "microcontrollers",
    "technical-discovery",
    "accounts-payable",
    "talent-management",
  ],
  "Backend & APIs": [
    "api",
    "rest",
    "spring",
    "microservices",
    "dotnet",
    "distributed-systems",
    "event-driven-architecture",
    "design-patterns",
    "fastapi",
    "maven",
    "oop",
    "laravel",
    "serverless",
    "cli",
    "json",
    "api-design",
    "postman",
    "django",
    "openapi",
    "rails",
    "grpc",
    "quarkus",
    "yaml",
    "jvm",
    "distributed-computing",
    "jpa",
    "xml",
    "hibernate",
    "flask",
    "symfony",
    "gradle",
    "hpc",
    "multithreading",
  ],
  "Ways of working": [
    "agile",
    "scrum",
    "jira",
    "developer-experience",
    "prototyping",
    "user-stories",
    "solution-design",
    "itil",
    "process-improvement",
    "program-management",
    "sdlc",
    "confluence",
    "kanban",
    "acceptance-criteria",
    "proof-of-concept",
    "scada",
    "user-research",
    "requirements-gathering",
    "pmp",
    "slack",
    "zoom",
    "atlassian",
    "wireframing",
    "design-thinking",
    "certified-scrummaster",
    "six-sigma",
    "uml",
    "professional-scrum-master",
  ],
  "Analytics & BI": [
    "analytics",
    "powerbi",
    "data-analytics",
    "tableau",
    "statistics",
    "data-visualization",
    "looker",
    "google-analytics",
    "ab-testing",
    "qlik",
    "time-series",
    "feature-engineering",
    "power-query",
    "predictive-analytics",
    "gis",
    "signal-processing",
  ],
  "Security & identity": [
    "cybersecurity",
    "iam",
    "gdpr",
    "devsecops",
    "vault",
    "authentication",
    "iso-27001",
    "firewall",
    "cloud-security",
    "oauth",
    "active-directory",
    "cisco",
    "cissp",
    "rbac",
    "dns",
    "zero-trust",
    "blockchain",
    "network-security",
    "tcp-ip",
    "openid",
    "soc-2",
    "cism",
    "secrets-management",
    "entra-id",
    "bgp",
    "pki",
    "vpn",
    "ccpa",
    "secure-coding",
    "sso",
    "web3",
    "owasp",
    "siem",
    "ethernet",
    "nist",
    "cryptocurrency",
    "saml",
    "wan",
    "fortinet",
    "jwt",
    "tls",
    "dhcp",
    "dlp",
    "okta",
    "scim",
  ],
  Frontend: [
    "react",
    "accessibility",
    "angular",
    "nodejs",
    "html",
    "backbone",
    "css",
    "vue",
    "nextjs",
    "graphql",
    "unity",
    "shopify",
    "express",
    "wordpress",
    "webhooks",
    "mvc",
    "npm",
    "wcag",
  ],
  "Databases & storage": [
    "postgresql",
    "oracle",
    "sql-server",
    "mysql",
    "nosql",
    "bigquery",
    "mongodb",
    "redis",
    "elasticsearch",
    "redshift",
    "clickhouse",
    "opensearch",
    "rds",
    "dynamodb",
    "neo4j",
    "db2",
    "cassandra",
  ],
  "Testing & quality": [
    "test-automation",
    "unit-testing",
    "tdd",
    "playwright",
    "junit",
    "selenium",
    "cypress",
    "bdd",
    "sonarqube",
    "pytest",
    "cucumber",
    "jest",
    "appium",
    "robot-framework",
  ],
  Mobile: ["android", "ios"],
} as const;

const SPECIAL_SKILL_LABELS: Record<string, string> = {
  ai: "AI",
  api: "API",
  aws: "AWS",
  bdd: "BDD",
  bgp: "BGP",
  cad: "CAD",
  cdk: "CDK",
  "ci-cd": "CI/CD",
  cli: "CLI",
  cmdb: "CMDB",
  cpp: "C++",
  crm: "CRM",
  csharp: "C#",
  css: "CSS",
  dbt: "dbt",
  dhcp: "DHCP",
  dns: "DNS",
  ec2: "EC2",
  ecs: "ECS",
  eks: "EKS",
  elk: "ELK",
  elt: "ELT",
  erp: "ERP",
  etl: "ETL",
  figma: "Figma",
  finops: "FinOps",
  fpga: "FPGA",
  gcp: "GCP",
  gdpr: "GDPR",
  gis: "GIS",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  gitops: "GitOps",
  gke: "GKE",
  grpc: "gRPC",
  hadoop: "Hadoop",
  helm: "Helm",
  hpc: "HPC",
  html: "HTML",
  iam: "IAM",
  ios: "iOS",
  itil: "ITIL",
  java: "Java",
  javascript: "JavaScript",
  jax: "JAX",
  jest: "Jest",
  jira: "Jira",
  json: "JSON",
  junit: "JUnit",
  jvm: "JVM",
  jwt: "JWT",
  kafka: "Kafka",
  kubernetes: "Kubernetes",
  lambda: "Lambda",
  llm: "LLM",
  mdm: "MDM",
  mlflow: "MLflow",
  mlops: "MLOps",
  mvc: "MVC",
  nats: "NATS",
  nginx: "NGINX",
  nist: "NIST",
  nlp: "NLP",
  nosql: "NoSQL",
  npm: "npm",
  oauth: "OAuth",
  oop: "OOP",
  openai: "OpenAI",
  openapi: "OpenAPI",
  opentelemetry: "OpenTelemetry",
  pki: "PKI",
  pmp: "PMP",
  postgresql: "PostgreSQL",
  powerbi: "Power BI",
  python: "Python",
  qlik: "Qlik",
  rag: "RAG",
  rbac: "RBAC",
  rds: "RDS",
  redis: "Redis",
  rest: "REST",
  rhel: "RHEL",
  rpa: "RPA",
  saas: "SaaS",
  saml: "SAML",
  sap: "SAP",
  "sap-s4hana": "SAP S/4HANA",
  sas: "SAS",
  sccm: "SCCM",
  scada: "SCADA",
  scim: "SCIM",
  sdlc: "SDLC",
  seo: "SEO",
  siem: "SIEM",
  sns: "SNS",
  "soc-2": "SOC 2",
  sql: "SQL",
  "sql-server": "SQL Server",
  sqs: "SQS",
  sso: "SSO",
  "tcp-ip": "TCP/IP",
  tdd: "TDD",
  tls: "TLS",
  typescript: "TypeScript",
  uipath: "UiPath",
  uml: "UML",
  unix: "Unix",
  vba: "VBA",
  vmware: "VMware",
  vpn: "VPN",
  vpc: "VPC",
  vue: "Vue",
  wan: "WAN",
  wcag: "WCAG",
  xml: "XML",
  yaml: "YAML",
};

export const PROFILE_SKILL_CATEGORIES = Object.keys(PROFILE_SKILLS_BY_CATEGORY);

export const PROFILE_SKILL_OPTIONS: ProfileSkillOption[] = Object.entries(
  PROFILE_SKILLS_BY_CATEGORY,
).flatMap(([category, values]) => values.map((value) => ({ category, value })));

export const PROFILE_SKILL_VALUES = new Set(
  PROFILE_SKILL_OPTIONS.map((skill) => skill.value),
);

const LEGACY_PROFILE_SKILL_VALUES: Record<string, string> = {
  React: "react",
  TypeScript: "typescript",
  JavaScript: "javascript",
  "Next.js": "nextjs",
  HTML: "html",
  CSS: "css",
  "Node.js": "nodejs",
  Java: "java",
  "Spring Boot": "spring",
  Python: "python",
  SQL: "sql",
  PostgreSQL: "postgresql",
  Git: "git",
  Docker: "docker",
  "REST API": "rest",
  Figma: "figma",
  "Data Analysis": "data-analytics",
  "Power BI": "powerbi",
  Azure: "azure",
  AWS: "aws",
};

export function normalizeProfileSkillsForCompatibility(skills: string[]) {
  return skills.reduce<string[]>((normalizedSkills, skill) => {
    const compatibleSkill = LEGACY_PROFILE_SKILL_VALUES[skill] ?? skill;

    if (!normalizedSkills.includes(compatibleSkill)) {
      normalizedSkills.push(compatibleSkill);
    }

    return normalizedSkills;
  }, []);
}

export function formatProfileSkillLabel(value: string) {
  if (SPECIAL_SKILL_LABELS[value]) {
    return SPECIAL_SKILL_LABELS[value];
  }

  return value
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
